### PR TITLE
Add a nonblocking LED display driver (draft 2)

### PR DESCRIPTION
**Pull request by mattheww**
Supersedes PR #14

This version is based on the new `HiResTimer` implementation in nrf51-hal (Cargo.toml specifies `nrf51-hal = "0.6.0"` but it really needs today's master to build).

This is the core of the code from <https://github.com/mattheww/microbit-blinkenlights>, as discussed in #13.

I've left out the font and scrolling support to start with.

Notes:

* I haven't done anything with the existing 'blocking' led.rs module.

* The rustdoc is using RFC1946-style links, which aren't stable but do work on docs.rs . I can remove those if you don't want to require nightly rustdoc.

### CODE REVIEW

**Comment by therealprof** [comment]
> This version is based on the new HiResTimer implementation in nrf51-hal (Cargo.toml specifies nrf51-hal = "0.6.0" but it really needs today's master to build).

I've just published a new 0.6.2 version.

> The rustdoc is using RFC1946-style links, which aren't stable but do work on docs.rs . I can remove those if you don't want to require nightly rustdoc.

I'm not sure which version is currently utilised by crates.io but I would assume it's nightly so that should be fine.

Other than that, looks excellent to me. Thanks a lot!

**Comment by mattheww** [comment]
As I understand it docs.rs uses nightly rustdoc, yes.

**Comment by therealprof** [comment]
Love the example. 👍

**Comment by david-sawatzke** [comment]
@therealprof This looks like it's ready to merge (and the example does look great)

**Comment by therealprof** [comment]
Hmm, completely forgot about this. @mattheww Can you resolve the merge conflicts?

**Comment by mattheww** [comment]
I've resolved the merge conflicts.

**Comment by therealprof** [comment]
I've merged it manually to get rid of the merge commit, thanks.

**Pull request closed without merging**
